name: ML pipeline (MLflow CI)

on:
  push:
    branches: [ "main" ]

jobs:
  ml_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 📦 Install deps
        run: |
          make install

      - name: ⬇️ Download dataset (UCI Wine Quality - red)
        run: |
          mkdir -p data
          curl -L "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv" -o data/winequality-red.csv

      - name: 🧪 Train
        env:
          # Forzamos a train.py a usar el CSV local si quieres modificarlo:
          # (Opcional) puedes dejarlo así tal cual, el script usa la URL de config.yaml
          # y también funciona.
          # DATA_PATH: data/winequality-red.csv
          # (si lo usas, modifica train.py para priorizar DATA_PATH sobre config.yaml)
          DUMMY: ok
        run: |
          make train

      - name: ✅ Validate
        run: |
          make test

      - name: 📤 Upload artifacts (model + metrics)
        uses: actions/upload-artifact@v4
        with:
          name: model-and-metrics
          path: artifacts/
